apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dm-app
  template:
    metadata:
      labels:
        app: dm-app
    spec:
      containers:
      - name: cont-1
        image: shaikmustafa/cycle
        ports:
        - containerPort: 80
